### ISSUE TITLE
App installation failed (sort of..)

### ISSUE THREAD

**Issue by merlijn-sebrechts** [rgv151/hn#1]
After installing the app, when opening the app in the store scope, the install button is still present. I want to leave a good review but can't because of this...

**Comment by ba0f3** [comment]
thank you for you interesting, I got same problem too, but I think it happened to me only (the author), I looking for help on Ubuntu Dev channels, and will update you as soon as it fixed

once again, thank you for your feedback

**Comment by ba0f3** [comment]
I just updated the app, you can review it now. Please remove old version first (just in case)

Thank you!

**Comment by merlijn-sebrechts** [comment]
Awesome. Thanks!
