### ISSUE TITLE
Special characters not displayed correctly

### ISSUE THREAD

**Issue by merlijn-sebrechts** [rgv151/hn#2]
As seen in the screenshot characters like ' are not displayed correctly. Not sure of this is a readability or a hn app issue.

![screenshot20160724_230424977](https://cloud.githubusercontent.com/assets/1492981/17086479/4df0432e-51f3-11e6-90f4-bb1c47e981ae.png)

**Comment by ba0f3** [comment]
i  think my readability service not handle unicode correctly, I will fix it soon, thank you!

**Comment by ba0f3** [comment]
improved readability integration
